
POST  http://localhost:3001/api/skuitem
Content-Type: application/json


    {
            "RFID":"12345678901234567890123456789015",
            "SKUId":1,
            "DateOfStock":"2021/11/29 12:30"
    }